# Generated by Django 4.1.7 on 2023-05-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_status_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_status',
            name='mobile',
        ),
    ]
