# Generated by Django 4.1.7 on 2023-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('book_quantity', models.IntegerField()),
                ('clothes_quantity', models.IntegerField()),
                ('electronics_quantity', models.IntegerField()),
                ('description', models.JSONField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
