# Generated by Django 4.1.7 on 2023-04-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='description',
            new_name='items',
        ),
    ]
